export const SITE_URL = 'https://cagm-website.vercel.app'

/** localStorage key of the visitor's light/dark choice */
export const THEME_STORAGE_KEY = 'cagm:theme'

export const PROFILE = {
  name: 'Carlos García',
  email: 'carlosgarcia.cagm@gmail.com',
  phone: '593967590148',
  phoneDisplay: '+593 967 590 148',
  /** first day as a professional developer; years of experience count from here */
  careerStart: '2019-01-26',
  city: 'Guayaquil',
  country: 'EC',
  linkedin: 'https://www.linkedin.com/in/carlosgarcia-cagm/',
  github: 'https://github.com/carlosgarcia-cagm'
} as const

/**
 * Full years of experience at `now`: it goes up on each anniversary of
 * `careerStart`, not on January 1st.
 */
export function yearsOfExperience(now: Date = new Date()): number {
  const [year, month, day] = PROFILE.careerStart.split('-').map(Number) as [number, number, number]
  const anniversaryReached =
    now.getMonth() + 1 > month || (now.getMonth() + 1 === month && now.getDate() >= day)
  return now.getFullYear() - year - (anniversaryReached ? 0 : 1)
}

/** Replaces `{years}` in CV texts outside vue-i18n (server, PDF, chat prompt). */
export function fillProfileValues(text: string, now?: Date): string {
  return text.replaceAll('{years}', String(yearsOfExperience(now)))
}

export type ContactKey = 'linkedin' | 'github' | 'email' | 'whatsapp' | 'telegram'

export interface ContactLink {
  key: ContactKey
  href: string
  icon: string
  label: string
  external: boolean
}

const CONTACT_ICONS: Record<ContactKey, string> = {
  linkedin: 'simple-icons:linkedin',
  github: 'simple-icons:github',
  email: 'material-symbols:mail-outline',
  whatsapp: 'simple-icons:whatsapp',
  telegram: 'simple-icons:telegram'
}

const CONTACT_HREFS: Record<ContactKey, string> = {
  linkedin: PROFILE.linkedin,
  github: PROFILE.github,
  email: `mailto:${PROFILE.email}`,
  whatsapp: `https://wa.me/${PROFILE.phone}`,
  telegram: `https://t.me/+${PROFILE.phone}`
}

/**
 * Builds the contact links shown in the hero and footer, in the given order.
 * `label` returns the translated accessible name of each link.
 */
export function buildContactLinks(
  keys: ContactKey[],
  label: (key: ContactKey) => string
): ContactLink[] {
  return keys.map((key) => ({
    key,
    href: CONTACT_HREFS[key],
    icon: CONTACT_ICONS[key],
    label: label(key),
    external: key !== 'email'
  }))
}

/** Path of the Harvard CV PDF for a locale, generated by server/routes/cv/[file].get.ts. */
export function cvDownloadPath(locale: string): string {
  return `/cv/carlos-garcia-cv-${locale === 'es' ? 'es' : 'en'}.pdf`
}

/** Absolute URL of a locale's home page (`en` is the default locale, served at `/`). */
export function localeUrl(locale: string): string {
  return locale === 'en' ? `${SITE_URL}/` : `${SITE_URL}/${locale}`
}

/** schema.org `Person` structured data for search engines. */
export function buildPersonJsonLd(options: {
  locale: string
  jobTitle: string
  description: string
  skills: string[]
}) {
  return {
    '@context': 'https://schema.org',
    '@type': 'Person',
    name: PROFILE.name,
    url: localeUrl(options.locale),
    image: `${SITE_URL}/og-image.png`,
    email: `mailto:${PROFILE.email}`,
    jobTitle: options.jobTitle,
    description: options.description,
    address: {
      '@type': 'PostalAddress',
      addressLocality: PROFILE.city,
      addressCountry: PROFILE.country
    },
    sameAs: [PROFILE.linkedin, PROFILE.github],
    knowsAbout: options.skills
  }
}
